[package]
name = "eldoria"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.49"
toml = "0.8.1"
