[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version="1.37.0", features=["full"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
rand = "0.8.5"
bincode = "1.3.3"
anyhow = "1.0.82"
