name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          (cd eldoria || git clone http://github.com/cowboy8625/eldoria && cd eldoria) &&
          git pull origin main &&
          cd ts_mud_server &&
          bun i &&
          bun run start

